name: Check Outer Wilds mod
description: Checks an Outer Wilds mod for common errors and warnings
author: Ben C <bwc9876@gmail.com>

inputs:
  sourceType:
    description: The type of source to pull the mod from (`repo`, `url`, or `zip`)
    required: true
  source:
    description: The source of the mod
    required: true
  expectedUniqueName:
    description: The expected unique name of the mod
    required: false
    default: ""
  skipDuplicateCheck:
    description: Whether to skip the duplicate check
    required: false
    default: "false"
  token:
    description: "The GitHub token to use for downloading the action, defaults to workflow token"
    required: true
    default: ${{ github.token }}
  overrideName:
    description: "The name to use for the action, defaults to `Mod Checker`"
    required: false
    default: "Mod Checker"

outputs:
  resultJson:
    description: The JSON output of the action
    value: ${{ steps.run_action.outputs.resultJson }}

runs:
  using: "composite"
  steps:
    - name: Set reusable variables
      shell: bash
      run: |
        echo "action_repo=mods-checker" >> $GITHUB_ENV
        echo "action_org=Bwc9876" >> $GITHUB_ENV
        echo "binary_name=mods-checker" >> $GITHUB_ENV

    - name: Add binary extension
      shell: bash
      if: runner.os == 'Windows'
      run: echo "binary_name=${{ env.binary_name }}.exe" >> $GITHUB_ENV

    - name: Get Action Version
      id: get_action_version
      shell: pwsh
      run: |
        $finalComponent = Split-Path -Leaf ${{ github.action_path }}
        if ($finalComponent -eq "${{ env.action_repo }}") {
          $version = ""
        } else {
          $version = $finalComponent
        }
        Write-Output "version=$version" >> $Env:GITHUB_OUTPUT

    - name: Download Action
      shell: bash
      run: |
        gh release download --repo ${{ env.action_org }}/${{ env.action_repo }} --pattern '${{ runner.os }}.tgz'
        tar -xzf ${{ runner.os }}.tgz
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Run Action
      id: run_action
      shell: bash
      run: echo "resultJson=$(./${{ runner.os }}/${{ env.binary_name }} --output-md --raw ${{ inputs.sourceType }} ${{ inputs.source }} ${{ inputs.expectedUniqueName != '' && format('--expected-unique-name={0}', inputs.expectedUniqueName) || '' }} ${{ inputs.skipDuplicateCheck == 'true' && '--skip-exists' || ''}})" >> $GITHUB_OUTPUT

    - name: Output Results
      uses: LouisBrunner/checks-action@v1.6.1
      env:
        summary_err: ${{ fromJson(steps.run_action.outputs.resultJson).error && 'Error Found.' || 'No Errors Found!' }}
      with:
        token: ${{ inputs.token }}
        name: ${{ inputs.overrideName }}
        conclusion: ${{ fromJson(steps.run_action.outputs.resultJson).error && 'failure' || 'success' }}
        output: |
          {"summary": "${{ format('Check Finished, {0}', env.summary_err) }}"}
        output_text_description_file: ./results.md

    - name: Exit with error if error found
      if: fromJson(steps.run_action.outputs.resultJson).error
      shell: bash
      run: exit 1
