name: Test Workflow

on:
  - workflow_dispatch

jobs:
  test_success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
            sourceType: repo
            source: Bwc9876/OW-TimeSaver
